import React from 'react';

// Simple presentational DischargeSummary component used by pages that
// render or print a discharge summary. Keeps markup minimal and resilient
// to variations in the `summary` / `patient` shapes returned by the API.
export default function DischargeSummary({ summary = {}, summaryDetails = null, patient = null }) {
  const s = summaryDetails || summary || {};
  const patientName = patient?.user?.name || patient?.name || s?.patientInfo?.name || 'Unknown Patient';
  const hospitalId = patient?.hospitalId || patient?.mrn || s?.patientInfo?.mrn || '';
  const admissionInfo = s?.admissionInfo || s?.admission || {};

  return (
    <div className="bg-white p-6 rounded-md shadow-sm text-sm">
      <h2 className="text-xl font-semibold mb-3">Discharge Summary</h2>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
        <div>
          <div className="text-gray-600">Patient</div>
          <div className="font-medium">{patientName}</div>
        </div>
        <div>
          <div className="text-gray-600">Hospital ID</div>
          <div className="font-medium">{hospitalId}</div>
        </div>
        <div>
          <div className="text-gray-600">Ward</div>
          <div className="font-medium">{admissionInfo.ward || admissionInfo.ward?.name || summary?.ward || 'N/A'}</div>
        </div>
      </div>

      <div className="mb-4">
        <div className="text-gray-600">Primary Diagnosis</div>
        <div className="font-medium">{s?.diagnosis?.primary || s?.diagnosis || s?.admissionDiagnosis || 'Not specified'}</div>
      </div>

      <div className="mb-4">
        <div className="text-gray-600">Clinical Summary / Hospital Stay</div>
        <div className="whitespace-pre-wrap">{s?.hospitalStaySummary || s?.summary || s?.hospitalCourse || s?.clinicalSummary || 'No summary provided.'}</div>
      </div>

      <div className="mb-4">
        <div className="text-gray-600">Medications on Discharge</div>
        <div className="whitespace-pre-wrap">
          {(() => {
            const meds = s?.medicationsOnDischarge || s?.medications || s?.medications || s?.medicationsOnDischarge || s?.medications || s?.dischargeMedication || [];
            if (Array.isArray(meds)) return meds.map(m => (m?.name || m)).join('\n');
            if (typeof meds === 'string') return meds;
            return 'No medications listed.';
          })()}
        </div>
      </div>

      {summary?.dischargeNotes && (
        <div className="mb-4">
          <div className="text-gray-600">Discharge Notes / Instructions</div>
          <div className="whitespace-pre-wrap">{summary.dischargeNotes}</div>
        </div>
      )}

      <div className="text-right text-xs text-gray-500">Generated by the Hospital Genz system</div>
    </div>
  );
}
